export const healthCheckupPackages = {
    featured: [
        {
            id: 1,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 104,
            title: "Tax Saver Package (Basic) - Family",
            ageGroup: "18-100yrs",
            price: 3499,
            originalPrice: 4374,
        },
        {
            id: 2,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 110,
            title: "Tax Saver Package (Advanced) - Family",
            ageGroup: "18-100yrs",
            price: 4999,
            originalPrice: 6249,
        },
        {
            id: 3,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 56,
            title: "Full Body Checkup",
            ageGroup: "18-60yrs",
            price: 1599,
            originalPrice: 1999,
        },
        {
            id: 4,
            discount: "15% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 72,
            title: "Complete Health Screening Package",
            ageGroup: "25-65yrs",
            price: 2199,
            originalPrice: 2599,
        },
        {
            id: 5,
            discount: "25% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 88,
            title: "Advanced Preventive Health Checkup",
            ageGroup: "30-70yrs",
            price: 2899,
            originalPrice: 3899,
        },
        {
            id: 6,
            discount: "18% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 65,
            title: "Executive Health Checkup",
            ageGroup: "25-60yrs",
            price: 2499,
            originalPrice: 3049,
        },
        {
            id: 7,
            discount: "22% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 48,
            title: "Essential Wellness Checkup",
            ageGroup: "18-50yrs",
            price: 1299,
            originalPrice: 1669,
        },
        {
            id: 8,
            discount: "12% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 58,
            title: "Heart & Lifestyle Health Package",
            ageGroup: "30-65yrs",
            price: 1899,
            originalPrice: 2149,
        },
        {
            id: 9,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 96,
            title: "Total Health Plus Package",
            ageGroup: "25-70yrs",
            price: 3199,
            originalPrice: 3999,
        },
        {
            id: 10,
            discount: "10% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 42,
            title: "Basic Preventive Health Checkup",
            ageGroup: "18-45yrs",
            price: 999,
            originalPrice: 1110,
        },
    ],

    womens: [
        {
            id: 11,
            discount: "25% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 64,
            title: "Women's Complete Health Checkup",
            ageGroup: "25-60yrs",
            price: 1899,
            originalPrice: 2499,
        },
        {
            id: 12,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 52,
            title: "Women's Wellness Package",
            ageGroup: "25-55yrs",
            price: 1499,
            originalPrice: 1874,
        },
        {
            id: 13,
            discount: "18% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 78,
            title: "Advanced Women's Health Package",
            ageGroup: "30-65yrs",
            price: 2299,
            originalPrice: 2799,
        },
        {
            id: 14,
            discount: "15% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 46,
            title: "Women's Essential Care Package",
            ageGroup: "18-45yrs",
            price: 1199,
            originalPrice: 1410,
        },
        {
            id: 15,
            discount: "22% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 61,
            title: "Women's Heart Health Checkup",
            ageGroup: "35-65yrs",
            price: 1799,
            originalPrice: 2299,
        },
        {
            id: 16,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 55,
            title: "Women's Diabetes Screening Package",
            ageGroup: "30-65yrs",
            price: 1399,
            originalPrice: 1749,
        },
        {
            id: 17,
            discount: "25% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 49,
            title: "Women's Thyroid & Wellness Checkup",
            ageGroup: "25-60yrs",
            price: 1299,
            originalPrice: 1729,
        },
        {
            id: 18,
            discount: "15% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 82,
            title: "Premium Women's Health Package",
            ageGroup: "30-70yrs",
            price: 2699,
            originalPrice: 3175,
        },
        {
            id: 19,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 44,
            title: "Women's Fitness Health Checkup",
            ageGroup: "18-40yrs",
            price: 1099,
            originalPrice: 1374,
        },
        {
            id: 20,
            discount: "30% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 91,
            title: "Women's Complete Wellness Plus",
            ageGroup: "25-70yrs",
            price: 2999,
            originalPrice: 4299,
        },
    ],

    mens: [
        {
            id: 21,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 68,
            title: "Men's Complete Health Checkup",
            ageGroup: "25-65yrs",
            price: 2099,
            originalPrice: 2599,
        },
        {
            id: 22,
            discount: "15% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 55,
            title: "Men's Wellness Package",
            ageGroup: "25-60yrs",
            price: 1699,
            originalPrice: 1999,
        },
        {
            id: 23,
            discount: "25% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 82,
            title: "Advanced Men's Health Package",
            ageGroup: "30-70yrs",
            price: 2499,
            originalPrice: 3299,
        },
        {
            id: 24,
            discount: "18% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 48,
            title: "Men's Essential Health Checkup",
            ageGroup: "18-50yrs",
            price: 1299,
            originalPrice: 1584,
        },
        {
            id: 25,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 63,
            title: "Men's Heart Health Package",
            ageGroup: "35-70yrs",
            price: 1899,
            originalPrice: 2374,
        },
        {
            id: 26,
            discount: "15% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 57,
            title: "Men's Diabetes Screening Package",
            ageGroup: "30-65yrs",
            price: 1499,
            originalPrice: 1764,
        },
        {
            id: 27,
            discount: "22% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 51,
            title: "Men's Liver & Kidney Health Checkup",
            ageGroup: "30-65yrs",
            price: 1599,
            originalPrice: 2049,
        },
        {
            id: 28,
            discount: "20% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 86,
            title: "Premium Men's Health Package",
            ageGroup: "30-70yrs",
            price: 2799,
            originalPrice: 3499,
        },
        {
            id: 29,
            discount: "12% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 43,
            title: "Men's Fitness Health Checkup",
            ageGroup: "18-45yrs",
            price: 1099,
            originalPrice: 1249,
        },
        {
            id: 30,
            discount: "28% OFF",
            image: "https://images1-fabric.practo.com/dx/labs/PRL-VDHC/logo.jpg/360x240",
            testsIncluded: 98,
            title: "Men's Complete Wellness Plus",
            ageGroup: "25-70yrs",
            price: 3199,
            originalPrice: 4449,
        },
    ],
};